@host = http://localhost:5242
@authorId = 0b23eb4b-5286-4f92-ae2e-374b65a50973
@postId = 96bd86d2-0e58-44a9-a972-76ffe24eb868

GET {{host}}/authors/

###

POST {{host}}/authors/
Content-Type: application/json

{
  "name": "Farllon"
}

###

GET {{host}}/authors/{{authorId}}

###

PUT {{host}}/authors/{{authorId}}
Content-Type: application/json

{
  "name": "Farllon 2"
}

###

DELETE {{host}}/authors/{{authorId}}

###

GET {{host}}/{{authorId}}/posts/

###

POST {{host}}/{{authorId}}/posts/
Content-Type: application/json

{
  "title": "Post 1",
  "content": "My first post",
  "authorId": "{{authorId}}"
}

###

GET {{host}}/{{authorId}}/posts/{{postId}}

###

PUT {{host}}/{{authorId}}/posts/{{postId}}
Content-Type: application/json

{
  "title": "Post 1",
  "content": "My first post changed",
  "authorId": "{authorId}"
}

###

DELETE {{host}}/{{authorId}}/posts/{{postId}}

###
